/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DataExample {
    }
    interface EventExampleContainer {
    }
    interface EventExampleCorrectChild {
        "count": number;
    }
    interface EventExampleWrongChild {
        "count": number;
    }
}
declare global {
    interface HTMLDataExampleElement extends Components.DataExample, HTMLStencilElement {
    }
    var HTMLDataExampleElement: {
        prototype: HTMLDataExampleElement;
        new (): HTMLDataExampleElement;
    };
    interface HTMLEventExampleContainerElement extends Components.EventExampleContainer, HTMLStencilElement {
    }
    var HTMLEventExampleContainerElement: {
        prototype: HTMLEventExampleContainerElement;
        new (): HTMLEventExampleContainerElement;
    };
    interface HTMLEventExampleCorrectChildElement extends Components.EventExampleCorrectChild, HTMLStencilElement {
    }
    var HTMLEventExampleCorrectChildElement: {
        prototype: HTMLEventExampleCorrectChildElement;
        new (): HTMLEventExampleCorrectChildElement;
    };
    interface HTMLEventExampleWrongChildElement extends Components.EventExampleWrongChild, HTMLStencilElement {
    }
    var HTMLEventExampleWrongChildElement: {
        prototype: HTMLEventExampleWrongChildElement;
        new (): HTMLEventExampleWrongChildElement;
    };
    interface HTMLElementTagNameMap {
        "data-example": HTMLDataExampleElement;
        "event-example-container": HTMLEventExampleContainerElement;
        "event-example-correct-child": HTMLEventExampleCorrectChildElement;
        "event-example-wrong-child": HTMLEventExampleWrongChildElement;
    }
}
declare namespace LocalJSX {
    interface DataExample {
    }
    interface EventExampleContainer {
    }
    interface EventExampleCorrectChild {
        "count"?: number;
    }
    interface EventExampleWrongChild {
        "count"?: number;
    }
    interface IntrinsicElements {
        "data-example": DataExample;
        "event-example-container": EventExampleContainer;
        "event-example-correct-child": EventExampleCorrectChild;
        "event-example-wrong-child": EventExampleWrongChild;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-example": LocalJSX.DataExample & JSXBase.HTMLAttributes<HTMLDataExampleElement>;
            "event-example-container": LocalJSX.EventExampleContainer & JSXBase.HTMLAttributes<HTMLEventExampleContainerElement>;
            "event-example-correct-child": LocalJSX.EventExampleCorrectChild & JSXBase.HTMLAttributes<HTMLEventExampleCorrectChildElement>;
            "event-example-wrong-child": LocalJSX.EventExampleWrongChild & JSXBase.HTMLAttributes<HTMLEventExampleWrongChildElement>;
        }
    }
}
