/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ComponentDefinition } from "../../../libs/core/src/index";
export { ComponentDefinition } from "../../../libs/core/src/index";
export namespace Components {
    interface DynamicComponent {
        "componentDef": ComponentDefinition;
        "props": Record<string, unknown>;
    }
    interface MockExample {
    }
    interface StencilRoot {
    }
}
declare global {
    interface HTMLDynamicComponentElement extends Components.DynamicComponent, HTMLStencilElement {
    }
    var HTMLDynamicComponentElement: {
        prototype: HTMLDynamicComponentElement;
        new (): HTMLDynamicComponentElement;
    };
    interface HTMLMockExampleElement extends Components.MockExample, HTMLStencilElement {
    }
    var HTMLMockExampleElement: {
        prototype: HTMLMockExampleElement;
        new (): HTMLMockExampleElement;
    };
    interface HTMLStencilRootElement extends Components.StencilRoot, HTMLStencilElement {
    }
    var HTMLStencilRootElement: {
        prototype: HTMLStencilRootElement;
        new (): HTMLStencilRootElement;
    };
    interface HTMLElementTagNameMap {
        "dynamic-component": HTMLDynamicComponentElement;
        "mock-example": HTMLMockExampleElement;
        "stencil-root": HTMLStencilRootElement;
    }
}
declare namespace LocalJSX {
    interface DynamicComponent {
        "componentDef"?: ComponentDefinition;
        "props"?: Record<string, unknown>;
    }
    interface MockExample {
    }
    interface StencilRoot {
    }
    interface IntrinsicElements {
        "dynamic-component": DynamicComponent;
        "mock-example": MockExample;
        "stencil-root": StencilRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dynamic-component": LocalJSX.DynamicComponent & JSXBase.HTMLAttributes<HTMLDynamicComponentElement>;
            "mock-example": LocalJSX.MockExample & JSXBase.HTMLAttributes<HTMLMockExampleElement>;
            "stencil-root": LocalJSX.StencilRoot & JSXBase.HTMLAttributes<HTMLStencilRootElement>;
        }
    }
}
